//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ShoppingDomainServiceData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShoppingDomainServiceDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShoppingDomainServiceDataObjectContext object using the connection string found in the 'ShoppingDomainServiceDataObjectContext' section of the application configuration file.
        /// </summary>
        public ShoppingDomainServiceDataObjectContext() : base("name=ShoppingDomainServiceDataObjectContext", "ShoppingDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoppingDomainServiceDataObjectContext object.
        /// </summary>
        public ShoppingDomainServiceDataObjectContext(string connectionString) : base(connectionString, "ShoppingDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoppingDomainServiceDataObjectContext object.
        /// </summary>
        public ShoppingDomainServiceDataObjectContext(EntityConnection connection) : base(connection, "ShoppingDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
