//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CreateNewOrder
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewOrder() : base("LightSwitchApplication:CreateNewOrder")
        {
            global::LightSwitchApplication.CreateNewOrder.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewOrder CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewOrder(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewOrder_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Customers_SelectionChanged();

        partial void Customers_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Loaded(bool succeeded);

        partial void Products_SelectionChanged();

        partial void Products_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Products_Loaded(bool succeeded);

        partial void Orders_SelectionChanged();

        partial void Orders_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Customers visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Customer> Customers
        {
            get
            {
                return global::LightSwitchApplication.CreateNewOrder.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Customers);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Products visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Product> Products
        {
            get
            {
                return global::LightSwitchApplication.CreateNewOrder.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Products);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Products_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Orders visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Order> Orders
        {
            get
            {
                return global::LightSwitchApplication.CreateNewOrder.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Orders);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewOrder.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewOrder.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Customers;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>.Entry
                __CreateNewOrderEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeCreated,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeActivated,
                    global::LightSwitchApplication.CreateNewOrder.DetailsClass.__CreateNewOrder_InvokeSaveErrorEvent);
            private static void __CreateNewOrder_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewOrder s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewOrder_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewOrder_InvokeSavingEvent(global::LightSwitchApplication.CreateNewOrder s)
            {
                bool handled = false;
                s.CreateNewOrder_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewOrder_InvokeSavedEvent(global::LightSwitchApplication.CreateNewOrder s)
            {
                s.CreateNewOrder_Saved();
            }
            private static bool __CreateNewOrder_InvokeClosingEvent(global::LightSwitchApplication.CreateNewOrder s)
            {
                bool cancel = false;
                s.CreateNewOrder_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewOrder_InvokeCreated(global::LightSwitchApplication.CreateNewOrder s)
            {
                s.CreateNewOrder_Created();
            }
            private static void __CreateNewOrder_InvokeActivated(global::LightSwitchApplication.CreateNewOrder s)
            {
                s.CreateNewOrder_Activated();
            }
            private static bool __CreateNewOrder_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewOrder s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewOrder_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewOrder.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewOrder.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CustomersQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Customers;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ProductsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Products;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable OrdersQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        this.Screen.DataWorkspace.ApplicationData.Orders,
                        "Customer"),
                    "Product");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product>.Data _Products;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order>.Data _Orders;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer> Customers
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer>)base.GetItem(global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Customers);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product> Products
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product>)base.GetItem(global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Products);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order> Orders
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order>)base.GetItem(global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties.Orders);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers",
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_Stub,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_Validate,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_CreateQuery,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_SelectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_OnCollectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Customers_OnLoaded);
                private static void _Customers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers, sf);
                }
                private static void _Customers_Validate(global::LightSwitchApplication.CreateNewOrder s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Customers_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Customers_CreateQuery(global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object[] args)
                {
                    return d.CustomersQuery();
                }
                private static void _Customers_SelectionChanged(global::LightSwitchApplication.CreateNewOrder s)
                {
                    s.Customers_SelectionChanged();
                }
                private static void _Customers_OnCollectionChanged(global::LightSwitchApplication.CreateNewOrder s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Customers_Changed(e);
                }
                private static void _Customers_OnLoaded(global::LightSwitchApplication.CreateNewOrder s, bool succeeded)
                {
                    s.Customers_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products",
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_Stub,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_Validate,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_CreateQuery,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_SelectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_OnCollectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Products_OnLoaded);
                private static void _Products_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object sf)
                {
                    c(d, ref d._Products, sf);
                }
                private static void _Products_Validate(global::LightSwitchApplication.CreateNewOrder s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Products_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Products_CreateQuery(global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object[] args)
                {
                    return d.ProductsQuery();
                }
                private static void _Products_SelectionChanged(global::LightSwitchApplication.CreateNewOrder s)
                {
                    s.Products_SelectionChanged();
                }
                private static void _Products_OnCollectionChanged(global::LightSwitchApplication.CreateNewOrder s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Products_Changed(e);
                }
                private static void _Products_OnLoaded(global::LightSwitchApplication.CreateNewOrder s, bool succeeded)
                {
                    s.Products_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order>.Entry
                    Orders = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order>.Entry(
                        "Orders",
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_Stub,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_Validate,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_CreateQuery,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_SelectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_OnCollectionChanged,
                        global::LightSwitchApplication.CreateNewOrder.DetailsClass.PropertySetProperties._Orders_OnLoaded);
                private static void _Orders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CreateNewOrder, global::LightSwitchApplication.CreateNewOrder.DetailsClass, global::LightSwitchApplication.Order>.Data> c, global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object sf)
                {
                    c(d, ref d._Orders, sf);
                }
                private static void _Orders_Validate(global::LightSwitchApplication.CreateNewOrder s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Orders_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Orders_CreateQuery(global::LightSwitchApplication.CreateNewOrder.DetailsClass d, object[] args)
                {
                    return d.OrdersQuery();
                }
                private static void _Orders_SelectionChanged(global::LightSwitchApplication.CreateNewOrder s)
                {
                    s.Orders_SelectionChanged();
                }
                private static void _Orders_OnCollectionChanged(global::LightSwitchApplication.CreateNewOrder s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Orders_Changed(e);
                }
                private static void _Orders_OnLoaded(global::LightSwitchApplication.CreateNewOrder s, bool succeeded)
                {
                    s.Orders_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CreateNewCustomer
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewCustomer() : base("LightSwitchApplication:CreateNewCustomer")
        {
            global::LightSwitchApplication.CreateNewCustomer.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewCustomer CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewCustomer(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCustomer_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CustomerProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Customer CustomerProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewCustomer.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties.CustomerProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewCustomer.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties.CustomerProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewCustomer.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewCustomer.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties.CustomerProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>.Entry
                __CreateNewCustomerEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeCreated,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeActivated,
                    global::LightSwitchApplication.CreateNewCustomer.DetailsClass.__CreateNewCustomer_InvokeSaveErrorEvent);
            private static void __CreateNewCustomer_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewCustomer s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewCustomer_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewCustomer_InvokeSavingEvent(global::LightSwitchApplication.CreateNewCustomer s)
            {
                bool handled = false;
                s.CreateNewCustomer_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewCustomer_InvokeSavedEvent(global::LightSwitchApplication.CreateNewCustomer s)
            {
                s.CreateNewCustomer_Saved();
            }
            private static bool __CreateNewCustomer_InvokeClosingEvent(global::LightSwitchApplication.CreateNewCustomer s)
            {
                bool cancel = false;
                s.CreateNewCustomer_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewCustomer_InvokeCreated(global::LightSwitchApplication.CreateNewCustomer s)
            {
                s.CreateNewCustomer_Created();
            }
            private static void __CreateNewCustomer_InvokeActivated(global::LightSwitchApplication.CreateNewCustomer s)
            {
                s.CreateNewCustomer_Activated();
            }
            private static bool __CreateNewCustomer_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewCustomer s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewCustomer_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewCustomer.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewCustomer.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer>.Data _CustomerProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer> CustomerProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer>)base.GetItem(global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties.CustomerProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    CustomerProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "CustomerProperty",
                        false,
                        global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties._CustomerProperty_Stub,
                        global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties._CustomerProperty_Validate,
                        global::LightSwitchApplication.CreateNewCustomer.DetailsClass.PropertySetProperties._CustomerProperty_OnValueChanged);
                private static void _CustomerProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCustomer, global::LightSwitchApplication.CreateNewCustomer.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.CreateNewCustomer.DetailsClass d, object sf)
                {
                    c(d, ref d._CustomerProperty, sf);
                }
                private static void _CustomerProperty_Validate(global::LightSwitchApplication.CreateNewCustomer s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CustomerProperty_Validate(r);
                }
                private static void _CustomerProperty_OnValueChanged(global::LightSwitchApplication.CreateNewCustomer s)
                {
                    s.CustomerProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CreateNewProduct
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewProduct() : base("LightSwitchApplication:CreateNewProduct")
        {
            global::LightSwitchApplication.CreateNewProduct.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewProduct CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewProduct(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewProduct_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void ProductProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Product ProductProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewProduct.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties.ProductProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewProduct.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties.ProductProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewProduct.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewProduct.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties.ProductProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>.Entry
                __CreateNewProductEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeCreated,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeActivated,
                    global::LightSwitchApplication.CreateNewProduct.DetailsClass.__CreateNewProduct_InvokeSaveErrorEvent);
            private static void __CreateNewProduct_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewProduct s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewProduct_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewProduct_InvokeSavingEvent(global::LightSwitchApplication.CreateNewProduct s)
            {
                bool handled = false;
                s.CreateNewProduct_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewProduct_InvokeSavedEvent(global::LightSwitchApplication.CreateNewProduct s)
            {
                s.CreateNewProduct_Saved();
            }
            private static bool __CreateNewProduct_InvokeClosingEvent(global::LightSwitchApplication.CreateNewProduct s)
            {
                bool cancel = false;
                s.CreateNewProduct_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewProduct_InvokeCreated(global::LightSwitchApplication.CreateNewProduct s)
            {
                s.CreateNewProduct_Created();
            }
            private static void __CreateNewProduct_InvokeActivated(global::LightSwitchApplication.CreateNewProduct s)
            {
                s.CreateNewProduct_Activated();
            }
            private static bool __CreateNewProduct_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewProduct s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewProduct_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewProduct.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewProduct.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product>.Data _ProductProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product> ProductProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product>)base.GetItem(global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties.ProductProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    ProductProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "ProductProperty",
                        false,
                        global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties._ProductProperty_Stub,
                        global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties._ProductProperty_Validate,
                        global::LightSwitchApplication.CreateNewProduct.DetailsClass.PropertySetProperties._ProductProperty_OnValueChanged);
                private static void _ProductProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewProduct, global::LightSwitchApplication.CreateNewProduct.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.CreateNewProduct.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductProperty, sf);
                }
                private static void _ProductProperty_Validate(global::LightSwitchApplication.CreateNewProduct s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.ProductProperty_Validate(r);
                }
                private static void _ProductProperty_OnValueChanged(global::LightSwitchApplication.CreateNewProduct s)
                {
                    s.ProductProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
